### ISSUE TITLE
[Module II] Option to manually change the random seed

### ISSUE THREAD

**Issue by jonnyishman** [jonathanlintott/Prospero#18]
From Trine.

**Comment by jonnyishman** [comment]
I assume this is for testing? I was hoping to avoid giving the user the ability to mess around with the inner workings of the noise generation.

**Comment by hklemm** [comment]
You have to be able to change the random seed as a user. Assume, I want to run Prospero on multiple machines to create more realisations in the same time that would be totally undermined by not being able to change the seed.

**Comment by jonnyishman** [comment]
Have added the ability to manually choose the seed for the noise map generation under the advanced settings. Default behaviour is to generate one pseudo-randomly. Let me know if all is okay and I will close the issue.

**Comment by hklemm** [comment]
Another nice option instead of generating the see pseudo-randomly is to use the current time down to the millisecond, or so.
