### ISSUE TITLE
[Module III] Missing modelling result

### ISSUE THREAD

**Issue by TrineDahl-Jensen** [jonathanlintott/Prospero#26]
Apparently in some cases the modelling result goes missing on the exceedance curve plot. No error message is given by Prospero. Changing seal leak to 0.5 the model appears again.
![screenshot_module_iii_missing_model](https://cloud.githubusercontent.com/assets/25099873/22823935/2fd3729a-ef86-11e6-8885-8d8e33d011f6.png)

**Comment by jonnyishman** [comment]
There used to be an error message but I removed it as it was quite annoying. I'll leave it up to Adam or Hanno if they want to put it back in. 

Either way it is clearly stated now in the 'Run Information' box if the log normal fit was successful or not. The main cause for an unsuccessful fit is if there is a large grouping of GRV values at the tail ends. You can see this in your example by the sharp gradient at the low end.
