### ISSUE TITLE
[Module IV] Colorbar and legend on map

### ISSUE THREAD

**Issue by TrineDahl-Jensen** [jonathanlintott/Prospero#27]
Add a colorbar and legend on the map. The legend would at the moment mainly bee to say what the outline is (I noticed it is not the same for the location and contact maps but don't know what it is exactly)

**Comment by jonnyishman** [comment]
I've added the colorbar on.

Regarding the outline you see, that's actually the contours for the plot. You'll notice it if you turn the contours on and off.
