### ISSUE TITLE
[Data Importer] Import multiple surfaces simultaneously 

### ISSUE THREAD

**Issue by jonnyishman** [jonathanlintott/Prospero#7]
From Trine.

**Comment by jonnyishman** [comment]
I could add in an option to load all surfaces from a specific folder. However, this would remove the ability to QC the individual surfaces before importing them into the Geocanopy Data Manager.

**Comment by TrineDahl-Jensen** [comment]
hmm.. I did not think about that. As long as the importer remembers the path of the last import it might be better to stick to loading one at a time.

**Comment by jonnyishman** [comment]
I've put the filepath fix in the data importer. Please let me know if that is sufficient or if you would still like a multi-surface import function.

**Comment by TrineDahl-Jensen** [comment]
Thanks, I think you can leave it at this for now, then we can always consider importing multiple surfaces at once later if needed.

**Comment by jonnyishman** [comment]
Great. Closing this for now. Let me know if it is something you want at a later date.
